spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profiledb
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    web: debug
    sql: error
    "[org.springframework.security]": trace
    "[com.hangout.core]": trace

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  instrumentation:
    micrometer:
      enabled: false

minio:
  url: http://localhost:9000
  accessKey: tvX2CSzBYVYWjeewgefr
  secretKey: 5isbCKPsmfKVa85VD1JRsnSWvoHjzcztGOxrEqMT

hangout:
  allowed-origins:
    url: http://localhost:5137/,
  media:
    upload-bucket: profile-photos
  auth-service:
    url: http://localhost:5011
