server:
  port: 5014
  servlet:
    context-path: /profile-api
spring:
  application:
    name: hangout-profile-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    web: error
    sql: error
    "[com.hangout.core]": trace
    # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  # All traces should be sent to latency analysis tool
  tracing:
    sampling:
      probability: 1.0
  otlp:
    # configures the endpoint to send OTLP metrics. (Does not support GRPC)
    metrics:
      export:
        url: ${OTEL_COLLECTOR}/v1/metrics
    tracing:
      compression: gzip

  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

otel:
  instrumentation:
    micrometer:
      enabled: true

minio:
  url: ${MINIO_SERVER}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

hangout:
  kafka:
    content:
      topic: ${CONTENT_TOPIC}
  allowed-origins:
    url: ${CLIENT_ORIGINS}
  media:
    upload-bucket: ${UPLOAD_BUCKET}
  auth-service:
    url: ${AUTH_SERVICE}
