spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profiledb
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    web: debug
    sql: error
    "[org.springframework.security]": trace
    "[com.hangout.core]": trace

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
  instrumentation:
    micrometer:
      enabled: true

minio:
  url: http://localhost:9000
  accessKey: tvX2CSzBYVYWjeewgefr
  secretKey: 5isbCKPsmfKVa85VD1JRsnSWvoHjzcztGOxrEqMT

hangout:
  kafka:
    content:
      topic: content
  allowed-origins:
    url: http://localhost:3000,
  media:
    upload-bucket: hangout-upload-path
  auth-service:
    url: http://localhost:5011
