name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  maven-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: maven

      - name: Cache Maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn package -DskipTests=true

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4

  build-image:
    needs: maven-package # makes sure maven-package is successfully completed before building the image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building the Docker image
        run: docker build . --file Dockerfile
